packages:
  - packages/*

nodeLinker: hoisted
verifyDepsBeforeRun: false

overrides:
  node-pty: npm:@lydell/node-pty@1.2.0-beta.15
  '@deepseek-ai/dsh-base>@deepseek-ai/dsh-subagent-claude-code': '-'
